name: Build Forklift

on:
  workflow_dispatch:
  push:
    branches:
      - "actions"
  pull_request:
    branches:
      - "main" 
    paths:
      - ".github/workflows/main.yaml"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: microsoft/setup-msbuild@v1.0.2

      - uses: ilammy/msvc-dev-cmd@v1.4.1
        with:
          arch: amd64
    
      - name: Set up vcpkg
        run: vcpkg integrate install
    
      - name: Build and install curl
        run: vcpkg install curl:x64-windows-static
    
      - name: Build and install jsoncpp
        run: vcpkg install jsoncpp:x64-windows-static
      
      - name: Compile Forklift
        run: msbuild Forklift.sln /p:Configuration=Manager_Release /property:Platform=x64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Forklift Build
          path: x64\Release

